### ISSUE TITLE
ggpmisc

### ISSUE THREAD

**Issue by aphalo** [erikgahner/awesome-ggplot2#20]
I appreciate you listed my packages 'ggpp' and 'ggspectra'.

I created package 'ggpp' by spliting the code of some geometries and position functions out of package 'ggpmisc'. Package 'ggpmisc' still imports and reexports the whole of 'ggpp'.  Package 'ggpmisc' is my most popular package, so I hope it could be added to the list, either in addition to 'ggpp' or instead of it. ('ggpmisc' has already 10 reverse dependencies.)

I have one more extenssion to 'ggplot2' in CRAN: 'gginnards'. This is more of a "niche" thing, and I am not sure whether it fits within the intended scope of this this.

**Comment by aphalo** [comment]
(https://github.com/aphalo/ggpmisc) and/or (https://docs.r4photobiology.info/ggpmisc/)
(https://github.com/aphalo/gginnards) and/or (https://docs.r4photobiology.info/gginnards/)

**Comment by erikgahner** [comment]
Both are great suggestions and I have added ggpmisc and gginnards to the overview. There is a certain overlap between the sections 'Plot layers' and 'Data and models', and I added them to the latter. However, do let me know if you believe they are a bitter fit in another section. Thanks again :)
