### ISSUE TITLE
More awesome packages

### ISSUE THREAD

**Issue by STF003** [erikgahner/awesome-ggplot2#25]
https://github.com/mitchelloharawild/ggquiver
https://github.com/hrbrmstr/ggsolar
https://github.com/BradyAJohnston/figpatch
https://github.com/eliocamp/ggperiodic
https://github.com/datacamp/ggdc
https://github.com/teunbrand/ggarrow
https://github.com/teunbrand/ggplot_tricks

**Comment by erikgahner** [comment]
Those are amazing, thank you very much! I have added them all.
