### ISSUE TITLE
More awesome packages

### ISSUE THREAD

**Issue by raivivek** [erikgahner/awesome-ggplot2#3]
Thanks for this repository. I was planning to create one but thankfully I searched before. Few packages that are useful (and seem popular) but do not currently exist in the list:

* ggbump - https://github.com/davidsjoberg/ggbump
* ggradar2 -- https://github.com/xl0418/ggradar2
* ggigraph -- https://github.com/davidgohel/ggiraph
* ggvegan -- https://github.com/gavinsimpson/ggvegan
* ggseg -- https://github.com/LCBC-UiO/ggseg
* ggwaffle -- https://github.com/liamgilbey/ggwaffle
* ggsn -- https://github.com/oswaldosantos/ggsn
* ggmotif -- https://github.com/AliciaSchep/ggmotif
* ggupset -- https://github.com/const-ae/ggupset
* ggtextures -- https://github.com/clauswilke/ggtextures
* ggannotate -- https://github.com/MattCowgill/ggannotate
* ggdendro -- https://github.com/andrie/ggdendro
* ggthreed -- https://github.com/coolbutuseless/ggthreed
* ggphylo -- https://github.com/gjuggler/ggphylo
* Potentially packages from here -- https://github.com/cgpu/awesome-ggplot

**Comment by erikgahner** [comment]
That's perfect! Thank you very much. I will make sure to add them all to the repository (and check out cgpu/awesome-ggplot for anything I might have missed). Thanks again!
