### ISSUE TITLE
Add ggfoundry

### ISSUE THREAD

**Issue by cgoo4** [erikgahner/awesome-ggplot2#34]
Please could you add [https://github.com/cgoo4/ggfoundry](https://github.com/cgoo4/ggfoundry).

**Comment by erikgahner** [comment]
The package is already included in the overview (under 'Icons, patterns and images'), cf. commit [80b4cbe](https://github.com/erikgahner/awesome-ggplot2/commit/80b4cbe4badc36f9b7f44de899f954554bde6c7d). Good job on the package -- it looks very promising!
