### ISSUE TITLE
Add all ggplot2 authors in "Persons" section?

### ISSUE THREAD

**Issue by batpigandme** [erikgahner/awesome-ggplot2#4]
Hi,

First of all, this is a great resource! Thanks so much for pulling it together.

It might be the case that the **Persons (+ Twitter)** section is meant to reflect people who are on twitter, and very knowledgeable about ggplot2, but I thought it might be worth including the authors and maintainers of the package as well ([listed here](https://ggplot2.tidyverse.org/authors.html)).

I don't know **Kohske Takahashi**'s Twitter handle, but as for the authors others who aren't on the list:
* **Winston Chang** is [@winston_chang](https://twitter.com/winston_chang),  
* **Lionel Henry** is [@_lionelhenry](https://twitter.com/_lionelhenry),  
* **Kara Woo** is [@kara_woo](https://twitter.com/kara_woo), and  
* **Hiroaki Yutani** is [@yutannihilat_en](https://twitter.com/yutannihilat_en).

As of the next release, **Dewey Dunnington** will also be listed as an author (already listed on the [ggplot2 dev-version site](https://ggplot2.tidyverse.org/dev/authors.html))! His twitter handle is [@paleolimbot](https://twitter.com/paleolimbot).

I'd be happy to submit a PR, if you'd like!

**Comment by erikgahner** [comment]
Hi,

Great idea! Thank you very much. I have added Winston, Lionel, Kara, Hiroaki and Dewey (alas, I couldn't find any useful info on Kohske Takahashi).

Thanks again! :-)
